name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: null
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.python_version }}'
          architecture: 'x64'
      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          version: 0.44.0
      - name: Install dependencies
        run: rye sync
      - name: Run tests
        run: rye run verify
