# See https://pre-commit.com/ for usage and config
default_language_version:
  python: python{{ cookiecutter.python_version }}
repos:
- repo: local
  hooks:
  - id: formatting
    name: formatting
    stages: [commit]
    language: system
    entry: rye run fmt
    pass_filenames: false
